import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

const formatTimestamp = (seconds = 0) => {
    const totalSeconds = Math.max(
        0,
        Math.floor(seconds)
    );

    const hours = Math.floor(
        totalSeconds / 3600
    );

    const minutes = Math.floor(
        (totalSeconds % 3600) / 60
    );

    const secs =
        totalSeconds % 60;

    if (hours > 0) {
        return [
            String(hours).padStart(2, "0"),
            String(minutes).padStart(2, "0"),
            String(secs).padStart(2, "0")
        ].join(":");
    }

    return [
        String(minutes).padStart(2, "0"),
        String(secs).padStart(2, "0")
    ].join(":");
};

const sanitizeTitle = (title = "video") => {
    return title
        .replace(/[<>:"/\\|?*\x00-\x1F]/g, "")
        .trim()
        .slice(0, 100) || "video";
};

/*
|--------------------------------------------------------------------------
| Generate Snapshot PDF
|--------------------------------------------------------------------------
*/

export const generateSnapshotPDF = ({
    videoTitle,
    videoUrl,
    snapshots,
    outputPath
}) => {

    return new Promise((resolve, reject) => {

        if (
            !Array.isArray(snapshots) ||
            snapshots.length === 0
        ) {
            reject(
                new Error(
                    "No snapshots available for PDF generation."
                )
            );

            return;
        }

        const doc = new PDFDocument({
            size: "A4",

            margins: {
                top: 45,
                bottom: 45,
                left: 45,
                right: 45
            },

            autoFirstPage: true,

            info: {
                Title:
                    `${videoTitle || "Video"} - Snapshots`,

                Author:
                    "AI Video Learning Generator",

                Subject:
                    "Distinct video snapshots"
            }
        });

        const stream =
            fs.createWriteStream(
                outputPath
            );

        doc.pipe(stream);

        /*
        ------------------------------------------------------------------
        Cover page
        ------------------------------------------------------------------
        */

        doc
            .font("Helvetica-Bold")
            .fontSize(26)
            .text(
                "Video Learning Snapshots",
                {
                    align: "center"
                }
            );

        doc.moveDown(1);

        doc
            .font("Helvetica-Bold")
            .fontSize(17)
            .text(
                videoTitle ||
                "YouTube Video",
                {
                    align: "center"
                }
            );

        doc.moveDown(1);

        doc
            .font("Helvetica")
            .fontSize(10)
            .fillColor("#555555")
            .text(
                `Total distinct snapshots: ${snapshots.length}`,
                {
                    align: "center"
                }
            );

        doc.moveDown(1);

        doc
            .fontSize(9)
            .text(
                videoUrl,
                {
                    align: "center",
                    width:
                        doc.page.width -
                        doc.page.margins.left -
                        doc.page.margins.right
                }
            );

        doc.fillColor("#000000");

        doc.moveDown(3);

        doc
            .fontSize(11)
            .text(
                "Generated by AI Video Learning Generator",
                {
                    align: "center"
                }
            );

        /*
        ------------------------------------------------------------------
        Snapshot pages
        ------------------------------------------------------------------
        */

        snapshots.forEach(
            (snapshot, index) => {

                doc.addPage();

                const pageWidth =
                    doc.page.width -
                    doc.page.margins.left -
                    doc.page.margins.right;

                const pageHeight =
                    doc.page.height -
                    doc.page.margins.top -
                    doc.page.margins.bottom;

                /*
                Header
                */

                doc
                    .font("Helvetica-Bold")
                    .fontSize(17)
                    .text(
                        `Snapshot ${index + 1}`,
                        doc.page.margins.left,
                        doc.page.margins.top
                    );

                doc
                    .font("Helvetica")
                    .fontSize(10)
                    .fillColor("#666666")
                    .text(
                        `Timestamp: ${formatTimestamp(
                            snapshot.timestamp
                        )}`
                    );

                doc.fillColor("#000000");

                /*
                Image area
                */

                const imageTop = 125;

                const imageBottom =
                    doc.page.height - 85;

                const imageHeight =
                    imageBottom - imageTop;

                try {

                    doc.image(
                        snapshot.path,
                        doc.page.margins.left,
                        imageTop,
                        {
                            fit: [
                                pageWidth,
                                imageHeight
                            ],

                            align: "center",

                            valign: "center"
                        }
                    );

                } catch (error) {

                    console.error(
                        `Failed to insert snapshot ${index + 1}:`,
                        error.message
                    );

                    doc
                        .font("Helvetica")
                        .fontSize(11)
                        .fillColor("#B00020")
                        .text(
                            "Unable to load this snapshot.",
                            doc.page.margins.left,
                            imageTop
                        );

                    doc.fillColor("#000000");
                }

                /*
                Footer
                */

                doc
                    .font("Helvetica")
                    .fontSize(8)
                    .fillColor("#777777")
                    .text(
                        `${index + 1} / ${snapshots.length}`,
                        doc.page.margins.left,
                        doc.page.height - 55,
                        {
                            width: pageWidth,
                            align: "center"
                        }
                    );

                doc.fillColor("#000000");
            }
        );

        /*
        ------------------------------------------------------------------
        Finish
        ------------------------------------------------------------------
        */

        doc.end();

        stream.on(
            "finish",
            () => {
                resolve({
                    path: outputPath,
                    filename:
                        `${sanitizeTitle(
                            videoTitle
                        )}-snapshots.pdf`
                });
            }
        );

        stream.on(
            "error",
            reject
        );
    });
};